server:
  port: 10094

spring:
  application:
    name: aiService
  profiles:
    active: dev
  webflux:
    base-path: /ai/api
  cloud:
    nacos:
      username: ${NACOS_USERNAME:nacos}
      password: ${NACOS_PASSWORD:nacos}
      server-addr: ${NACOS_SERVER_ADDR:localhost:8848}
      config:
        namespace: dev
      discovery:
        namespace: ${spring.cloud.nacos.config.namespace}
  config:
    import:
      - nacos:common-dev.yaml?group=DEFAULT_GROUP&refreshEnabled=true
      - nacos:ai-dev.yaml?group=DEFAULT_GROUP&refreshEnabled=true
logging:
  level:
    org.springframework.ai: DEBUG
